services:
  python:
    build:
      context: ./python
    restart: always
    devices:
       - /dev/ttyUSB0:/dev/ttyUSB0
    privileged: true
    depends_on: [graphite, mosquitto]
    volumes:
      - ./python:/usr/src/app
  graphite:
    image: graphiteapp/graphite-statsd
    container_name: graphite
    restart: always
    ports:
      - "2003-2004:2003-2004"
      - "8080:80"
    volumes:
      - ./graphite/storage-schemas.conf:/opt/graphite/conf/storage-schemas.conf
      - ./graphite/storage-aggregation.conf:/opt/graphite/conf/storage-aggregation.conf
      - ./graphite/data:/opt/graphite/storage/whisper
  grafana:
    restart: always
    image: grafana/grafana:9.0.8
    ports:
      - 3000:3000
    volumes:
      - ./grafana/lib:/var/lib/grafana
      - ./grafana/etc:/etc/grafana
      - ./grafana/log:/var/log/grafana
  mosquitto:
    image: eclipse-mosquitto
    restart: always
    volumes:
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
    ports:
      - 1883:1883
      - 9001:9001

