{
 "title": "Inverter",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Overview",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "alias": "Load",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "inverter",
     "query": "SELECT  FROM \"inverter\" WHERE $timeFilter GROUP BY time(10s) fill(null)",
     "select": [
      [
       { "params": [ "Plocalload" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "target": "alias(inverter.Plocalload, 'Load')"
    },
    {
     "alias": "pvPower",
     "query": "SELECT mean(\"Ppv\") FROM \"inverter\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "target": "alias(inverter.Ppv, 'Generation')"
    },
    {
     "alias": "Battery",
     "query": "SELECT (mean(\"Pcharge\")-mean(\"Pdischarge\")) as watts FROM \"inverter\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "target": "alias(diffSeries(inverter.Pcharge, inverter.Pdischarge), 'Battery')"
    },
    {
     "alias": "Grid",
     "query": "SELECT (mean(\"Pactouser\") - mean(\"Pactogrid\"))  as watts FROM \"inverter\" WHERE $timeFilter GROUP BY time(10s) fill(null)",
     "target": "alias(diffSeries(inverter.Pactouser, inverter.Pactogrid), 'Grid')"
    }
   ]
  },
  {
   "title": "Daily Overview",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "alias": "Load",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "inverter",
     "query": "SELECT  FROM \"inverter\" WHERE $timeFilter GROUP BY time(10s) fill(null)",
     "select": [
      [
       { "params": [ "Plocalload" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "target": "alias(inverter.Plocalload, 'Load')"
    },
    {
     "alias": "pvPower",
     "query": "SELECT mean(\"Ppv\") FROM \"inverter\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "target": "alias(inverter.Ppv, 'Generation')"
    },
    {
     "alias": "Battery",
     "query": "SELECT (mean(\"Pcharge\")-mean(\"Pdischarge\")) as watts FROM \"inverter\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "target": "alias(diffSeries(inverter.Pcharge, inverter.Pdischarge), 'Battery')"
    },
    {
     "alias": "Grid",
     "query": "SELECT (mean(\"Pactouser\") - mean(\"Pactogrid\"))  as watts FROM \"inverter\" WHERE $timeFilter GROUP BY time(10s) fill(null)",
     "target": "alias(diffSeries(inverter.Pactouser, inverter.Pactogrid), 'Grid')"
    }
   ]
  },
  {
   "title": "Battery SOC",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "Percent",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "inverter",
     "query": "SELECT mean(\"SOC\") as Percent FROM \"inverter\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "battSOC" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "target": "inverter.SOC"
    }
   ]
  },
  {
   "title": "Battery Charge",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "inverter",
     "select": [
      [
       { "params": [ "SOC" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "target": "inverter.SOC"
    }
   ]
  },
  {
   "title": "Battery Remain",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } }
  },
  {
   "title": "pvPower",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "target": "inverter.Ppv" }
   ]
  },
  {
   "title": "Load",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "target": "inverter.Plocalload" }
   ]
  },
  {
   "title": "PV 1+2",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 10, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "alias": "pv2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "inverter",
     "select": [
      [
       { "params": [ "Ppv1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "target": "inverter.Ppv1"
    },
    {
     "alias": "pv1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "inverter",
     "select": [
      [
       { "params": [ "Ppv2" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "target": "inverter.Ppv2"
    }
   ]
  },
  {
   "title": "Grid",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "diffSeries(inverter.Pactouser, inverter.Pactogrid)"
    }
   ]
  },
  {
   "title": "Battery",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "diffSeries(inverter.Pcharge, inverter.Pdischarge)"
    }
   ]
  }
 ]
}